server.port=9094
spring.application.name=authorization-service

sre-catalog.authz.opa-url=${OPA_URL:http://localhost:9181}
sre-catalog.authz.users-file=${USERS_FILE:/app/keycloak-seed/users.yaml}
sre-catalog.authz.compliance-roles=${COMPLIANCE_ROLES:COMPLIANCE_ANALYST,COMPLIANCE_OFFICER,PLATFORM_ADMIN}

sre-catalog.auth.keycloak-token-url=${KEYCLOAK_TOKEN_URL:http://localhost:9080/realms/sre-catalog/protocol/openid-connect/token}
sre-catalog.auth.keycloak-client-id=${KEYCLOAK_CLIENT_ID:sre-catalog-ui}
sre-catalog.auth.keycloak-client-secret=${KEYCLOAK_CLIENT_SECRET:}
sre-catalog.auth.authorized-service-user-ids=${AUTHORIZED_SERVICE_USER_IDS:svc-instruction,svc-payment}

management.endpoints.web.exposure.include=health,info,prometheus
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URL:http://localhost:9080/realms/sre-catalog}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:http://localhost:9080/realms/sre-catalog/protocol/openid-connect/certs}
