server.port=9094
spring.application.name=authorization-service

observability-mesh.authz.opa-url=${OPA_URL:http://localhost:9181}
observability-mesh.authz.users-file=${USERS_FILE:/app/keycloak-seed/users.yaml}
observability-mesh.authz.compliance-roles=${COMPLIANCE_ROLES:COMPLIANCE_ANALYST,COMPLIANCE_OFFICER,PLATFORM_ADMIN}

observability-mesh.auth.keycloak-token-url=${KEYCLOAK_TOKEN_URL:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/token}
observability-mesh.auth.keycloak-client-id=${KEYCLOAK_CLIENT_ID:observability-mesh-ui}
observability-mesh.auth.keycloak-client-secret=${KEYCLOAK_CLIENT_SECRET:}
observability-mesh.auth.authorized-service-user-ids=${AUTHORIZED_SERVICE_USER_IDS:svc-instruction,svc-payment}

management.endpoints.web.exposure.include=health,info,prometheus
otel.instrumentation.mongo.enabled=false
otel.instrumentation.spring-web.enabled=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URL:http://localhost:9080/realms/observability-mesh}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/certs}
