server.port=9095
spring.application.name=sequence-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/?replicaSet=rs0}
spring.data.mongodb.database=${MONGODB_DATABASE:ssi_sequences}
management.endpoints.web.exposure.include=health,info,prometheus
otel.instrumentation.mongo.enabled=false
otel.instrumentation.spring-web.enabled=false
otel.resource.attributes.service.name=${OTEL_SERVICE_NAME:sequence-service},deployment.environment=${OTEL_DEPLOYMENT_ENVIRONMENT:development}
