server.port=9090
spring.application.name=slo-author-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/open_slo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:open_slo}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:open_slo}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jackson.serialization.indent-output=true

observability-mesh.auth.keycloak-token-url=${KEYCLOAK_TOKEN_URL:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/token}
observability-mesh.auth.keycloak-client-id=${KEYCLOAK_CLIENT_ID:observability-mesh-ui}
observability-mesh.auth.keycloak-client-secret=${KEYCLOAK_CLIENT_SECRET:}

management.endpoints.web.exposure.include=health,info,prometheus
otel.instrumentation.mongo.enabled=false
otel.instrumentation.spring-web.enabled=false
otel.resource.attributes.service.name=${OTEL_SERVICE_NAME:slo-author-service},deployment.environment=${OTEL_DEPLOYMENT_ENVIRONMENT:development}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URL:http://localhost:9080/realms/observability-mesh}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/certs}
