server.port=9090
spring.application.name=slo-author-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/?replicaSet=rs0}
spring.data.mongodb.database=${MONGODB_DATABASE:open-slo}

spring.jackson.serialization.indent-output=true

observability-mesh.auth.keycloak-token-url=${KEYCLOAK_TOKEN_URL:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/token}
observability-mesh.auth.keycloak-client-id=${KEYCLOAK_CLIENT_ID:observability-mesh-ui}
observability-mesh.auth.keycloak-client-secret=${KEYCLOAK_CLIENT_SECRET:}

management.endpoints.web.exposure.include=health,info,prometheus
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
otel.resource.attributes.service.name=${OTEL_SERVICE_NAME:slo-author-service},deployment.environment=${OTEL_DEPLOYMENT_ENVIRONMENT:development}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URL:http://localhost:9080/realms/observability-mesh}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:http://localhost:9080/realms/observability-mesh/protocol/openid-connect/certs}
