server.port=9000
spring.application.name=instruction-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/?replicaSet=rs0}
spring.data.mongodb.database=${MONGODB_DATABASE:ssi_cash_instructions}

sre-catalog.instruction.collection=instructions
sre-catalog.instruction.security-events-database=security_events
sre-catalog.instruction.security-events-collection=instruction_service

sre-catalog.authz.url=${AUTHORIZATION_SERVICE_URL:http://localhost:9094}
sre-catalog.sequence.url=${SEQUENCE_SERVICE_URL:http://localhost:9095}

sre-catalog.auth.keycloak-token-url=${KEYCLOAK_TOKEN_URL:http://localhost:9080/realms/sre-catalog/protocol/openid-connect/token}
sre-catalog.auth.keycloak-client-id=${KEYCLOAK_CLIENT_ID:sre-catalog-ui}
sre-catalog.auth.keycloak-client-secret=${KEYCLOAK_CLIENT_SECRET:}

sre-catalog.instruction.service-user-id=${SERVICE_USER_ID:svc-instruction}
sre-catalog.instruction.service-user-password=${SERVICE_USER_PASSWORD:Password1!}

sre-catalog.instruction.compliance-roles=${COMPLIANCE_ROLES:COMPLIANCE_ANALYST,COMPLIANCE_OFFICER,PLATFORM_ADMIN}
sre-catalog.instruction.security-event-excluded-user-ids=${SECURITY_EVENT_EXCLUDED_USER_IDS:}
sre-catalog.instruction.security-event-view-excluded-user-ids=${SECURITY_EVENT_VIEW_EXCLUDED_USER_IDS:admin-001}
sre-catalog.instruction.ui-initial-security-event-limit=${UI_INITIAL_SECURITY_EVENT_LIMIT:200}

management.endpoints.web.exposure.include=health,info,prometheus
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
otel.exporter.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OIDC_ISSUER_URL:http://localhost:9080/realms/sre-catalog}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OIDC_JWK_SET_URI:http://localhost:9080/realms/sre-catalog/protocol/openid-connect/certs}
